blog/views/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import LoginManager, login_user, logout_user, login_required
from blog.models import User
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from sqlalchemy.exc import IntegrityError
from blog.models.database import db
from blog.models import User
from blog.forms.user import RegistrationForm
from werkzeug.exceptions import NotFound
from blog.forms.user import RegistrationForm, LoginForm

auth_app = Blueprint("auth_app", __name__)
login_manager = LoginManager()
login_manager.login_view = "auth_app.login"

@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).one_or_none()

@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for("auth_app.login"))

__all__ = [
"login_manager",
"auth_app",
]

# @auth_app.route("/login/", methods=["GET", "POST"], endpoint="login")
# def login():
#     if request.method == "GET":
#         return render_template("auth/login.html")
    
#     username = request.form.get("username")
#     if not username:
#         return render_template("auth/login.html", error="username not passed")
    
#     user = User.query.filter_by(username=username).one_or_none()
#     if user is None:
#         return render_template("auth/login.html", error=f"no user {username!r} found")

#     login_user(user)
#     return redirect(url_for("blog_app.index"))

@auth_app.route("/logout/", endpoint="logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("blog_app.index"))

@auth_app.route("/secret/")
def secret_view():
        return render_template("secret/data.html")

@auth_app.route("/register/", methods=["GET", "POST"], endpoint="register")
def register():
    if current_user.is_authenticated:
        return redirect("index")
    
    error = None
    form = RegistrationForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        if User.query.filter_by(username=form.username.data).count():
            form.username.errors.append("username already exists!")
            return render_template("auth/register.html", form=form)

        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email already exists!")
            return render_template("auth/register.html", form=form)
        
        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            is_staff=False,
        )
        user.password = form.password.data
        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            current_app.logger.exception("Could not create user!")
            error = "Could not create user!"
        else:
            current_app.logger.info("Created user %s", user)
            login_user(user)
            return redirect(url_for("index"))
    
    return render_template("auth/register.html", form=form, error=error)

@auth_app.route('/login', methods=('GET', 'POST'))
def login():
    if current_user.is_authenticated:
        return redirect("index")
    
    form = LoginForm(request.form)
    
    if request.method == "POST" and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one_or_none()
    
        if user is None:
            return render_template("auth/login.html", form=form, error="username doesn't exist")
        
        if not user.validate_password(form.password.data):
            return render_template("auth/login.html", form=form, error="invalid username or password")
        
        login_user(user)
        return redirect(url_for("index"))
    
    return render_template("auth/login.html", form=form)



@auth_app.route("/login-as/", methods=["GET", "POST"], endpoint="login-as")
def login_as():
    if not (current_user.is_authenticated and current_user.is_staff):
    # non-admin users should not know about this feature
        raise NotFound
    
 

blog/templates/base.html
<!DOCTYPE html>

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    

    <title>
        {% block title %}
            Base
        {% endblock %}
    </title>
  </head>
  <body>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
            
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    {% for (endpoint, label) in [('users_app.list', 'Users'), ('articles_app.list', 'Articles'), ('authors_app.list', 'Authors')] %}
                        <a href="{{ url_for(endpoint) }}" class="nav-link {% if request.endpoint == endpoint %}active{% endif %}">
                            {{ label }}
                        </a>
                    {% endfor %}
                </div>
                <div class="navbar-nav ms-auto">
                    {% if current_user.is_authenticated %}
                        <a class="nav-link" href="{{ url_for('auth_app.logout') }}">Logout</a>
                    {% else %}
                        <a href="{{ url_for('auth_app.login') }}" class="nav-link {% if request.endpoint == 'login' %}active{% endif %}">Login</a>
                    {% endif %}
                </div>
                <div class="navbar-nav ms-auto">
                    <a class="nav-link" href="{{ url_for('blog_app.index') }}">blog</a>
                </div>
                <div class="navbar-nav ms-auto">
                    <a class="nav-link" href="{{ url_for('auth_app.secret_view') }}">secret_data</a>
                </div>
                <div class="navbar-nav ms-auto">
                    {% for (endpoint, label) in [('auth_app.register', 'Register')] %}
                        <a href="{{ url_for(endpoint) }}" class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                            {{ label }}
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </nav>
    
    
    <div>
        {% block body %}
            Body base
        {% endblock %}
    </div>

    
  </body>
</html>

blog/templates/index.html
<!DOCTYPE html>

    
{% extends 'base.html' %}

{% block title %}
    Index page
{% endblock %}
    
{% block body %}
    <h1>
        Hello
        {% if current_user.is_authenticated %}
            {{ current_user.username }}
        {% else %}
            anon
        {% endif %}
    </h1>
{% endblock %}